export { IAnalysis } from './lib/analysis';
export { analyze } from './lib/analyze';
export { backtest } from './lib/backtest';
export { IBar } from './lib/bar';
export { computeDrawdown } from './lib/compute-drawdown';
export { computeEquityCurve } from './lib/compute-equity-curve';
export { monteCarlo } from './lib/monte-carlo';
export { IOptimizationResult, IParameterDef, ObjectiveFn, OptimizationType, optimize, OptimizeSearchDirection } from './lib/optimize';
export { IPosition } from './lib/position';
export { PositionManager } from './lib/position-manager';
export { IStrategy } from './lib/strategy';
export { ITrade } from './lib/trade';
export { walkForwardOptimize } from './lib/walk-forward-optimize';
